export const phrases = [
  "are you for real?",
  "helloooooooooooooooooooooooooooooooooooooooooooooooo",
  "protein",
  "uhh",
  "uwu.network",
  "i live in your walls",
  "hello world",
  "eepy",
  "beep boop",
  "meow meow",
  "sudo make me a sandwich",
  "touch grass",
  "skill issue",
  "*nuzzles your server rack*",
  "nya~",
  "where did I put my keys?",
  "coffee.exe has stopped working",
  "01101000 01101001",
  "loading personality.dll...",
  "error: task failed successfully",
  "have you tried turning it off and on again?",
  "404 motivation not found",
  "sudo apt-get install brain",
];
